name: testination
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: ^2.0.0
  carousel_slider: ^3.0.0
  cached_network_image: ^3.0.0
  flutter_spinkit: ^5.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
#  flutter_statusbarcolor: ^0.2.3
  timer_count_down: ^2.0.0
  flutter_boom_menu: ^1.0.2


  razorpay_flutter: ^1.2.5
  fluttertoast: ^8.0.3
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_auth: ^1.0.1
  flutter_typeahead: ^3.1.0
  font_awesome_flutter: ^9.0.0
  modal_progress_hud: ^0.1.3
  country_pickers: ^2.0.0
  pin_entry_text_field: ^0.1.4
  argon_buttons_flutter: ^1.0.6
  flutter_staggered_animations: ^1.0.0
  auto_size_text: ^2.1.0
  flutter_tex: ^3.6.7+10
  firebase_storage: ^8.0.1
  webview_flutter: ^1.0.3
#  libv_markdown: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

